- name: homebrew tap repository
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - "{{ homebrew_taps }}"

- name: update homebrew
  homebrew: 
    update_homebrew: yes
    upgrade_all: yes

- name: install packages
  homebrew: >
    name = {{ item.name }}
    state = {{ item.state | default("installed") }}
  with_items:
    - "{{ homebrew_packages  }}"

- name: install cask packages
  homebrew_cask: 
    name: "{{ item.name }}"
    state: "present"
    install_options: "appdir=/Applications"
    accept_external_apps: yes
  with_items:
    - "{{ homebrew_cask_packages }}"
  register: cask_result
